export const HELP = [
  { category: "Plans", question: "How does the free trial work?", answer: "The no-card trial lasts seven days and includes 25 publish/relist actions across your supported accounts, with no AI credits. Each destination uses an action when its job starts; retries of the same job do not charge another action. Expiry or an exhausted allowance stops new publishing, while inventory, edits and delisting remain available. There is no automatic payment at the end." },
  { category: "Getting started", question: "How do I crosslist my first item?", answer: "Connect a supported marketplace in Accounts. Import your item, open it in Products and review its photos, category and price. Choose a destination, fill the remaining required fields, save and publish. Check Activity for the result; a queued job is not a live listing." },
  { category: "Connections", question: "Which marketplaces can I connect?", answer: "This beta implements eBay UK and Vinted UK connection workflows. eBay uses seller authorization; Vinted uses the Lane browser or desktop bridge. Other services appear in the catalogue as planned integrations. All supported connections are included on every tier. Availability also depends on the deployment and your marketplace account." },
  { category: "Connections", question: "My account needs reconnecting. What should I do?", answer: "Open Accounts and read the status beside the affected shop. For eBay, reconnect through the official authorization window. For Vinted, sign in on the marketplace and keep the bridge available. Check Activity before retrying a publish so you do not accidentally create a duplicate." },
  { category: "AI", question: "Does AI make up missing details?", answer: "Field completion looks for details explicitly supported by your listing text. Suggestions show the supporting text and are checked against the category's permitted values. Review them before applying. If the source does not establish a fact, enter it yourself; AI should not guess material composition, measurements, condition or authenticity." },
  { category: "AI", question: "Can I use Lane without AI?", answer: "Yes. Starter has no AI credits and normal crosslisting remains manual. Seller and Pro include credits, but AI starts off. Enable it in Billing and choose when to request suggestions. It never publishes a listing for you." },
  { category: "AI", question: "What uses an AI credit?", answer: "A successful listing-copy request or useful field-completion response uses one credit. Failed requests restore the reservation, and field searches with no usable suggestions use no credit. Credits reset each UTC calendar month without rollover. A monthly provider-cost guard may pause AI before all credits are used, especially after repeated timeouts. No automatic credit purchases or overage charges." },
  { category: "Photos", question: "What can Photo studio do?", answer: "Rotate, square-crop, add breathing room and a white or warm frame, and adjust lighting and contrast. Processing runs on your device without an AI charge. A cleaned copy is added while the original stays. It does not remove a busy background or generate missing product details. Keep colours and flaws accurate." },
  { category: "Photos", question: "Why does an image need a public URL for eBay?", answer: "The current eBay publisher needs publicly accessible photos. Imported marketplace photos may provide these. New device uploads and edited copies stay in your draft as local image data until a supported hosting/upload route is available. Lane will explain this before publication; adding a local image is not proof it is ready for eBay." },
  { category: "Publishing", question: "Why are there different questions for eBay?", answer: "Each category has its own required details and allowed values. Lane requests the current eBay field schema, preserves information already supplied, and shows what is still missing. Basic field lookup and manual editing do not consume AI credits." },
  { category: "Publishing", question: "Will a sale automatically remove every other listing?", answer: "Lane has sale handling and delist jobs, but reliable unattended detection across all marketplaces is still being verified in this beta. Monitor Activity and your marketplaces. Do not assume that a queued delist has completed." },
  { category: "Plans", question: "Can I switch plans or cancel?", answer: "When subscriptions are enabled, use Manage subscription in Billing. The payment provider shows the effective date and any charges before confirmation. Existing subscriptions are not automatically moved to new advertised prices. During a local preview, prices are informational and the app cannot charge you." },
] as const;
