/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSoldRouteImport } from './routes/_app.sold'
import { Route as ApiWorkerRouteImport } from './routes/api/worker'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryIdRouteImport } from './routes/_app.inventory.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsChannelsRouteImport } from './routes/_app.settings.channels'
import { Route as AppSettingsPricingRulesRouteImport } from './routes/_app.settings.pricing-rules'
import { Route as AppSettingsShippingRouteImport } from './routes/_app.settings.shipping'
import { Route as AppSettingsTemplatesRouteImport } from './routes/_app.settings.templates'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBridgeSplatRouteImport } from './routes/api/bridge/$'
import { Route as ApiEbayCallbackRouteImport } from './routes/api/ebay/callback'
import { Route as ApiEbayStartRouteImport } from './routes/api/ebay/start'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ConnectVintedIdRouteImport } from './routes/connect.vinted.$id'
import { Route as ApiVintedConnectSplatRouteImport } from './routes/api/vinted/connect/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSoldRoute = AppSoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => AppRoute,
} as any)
const ApiWorkerRoute = ApiWorkerRouteImport.update({
  id: '/api/worker',
  path: '/api/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsChannelsRoute = AppSettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPricingRulesRoute = AppSettingsPricingRulesRouteImport.update({
  id: '/pricing-rules',
  path: '/pricing-rules',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShippingRoute = AppSettingsShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTemplatesRoute = AppSettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeSplatRoute = ApiBridgeSplatRouteImport.update({
  id: '/api/bridge/$',
  path: '/api/bridge/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbayCallbackRoute = ApiEbayCallbackRouteImport.update({
  id: '/api/ebay/callback',
  path: '/api/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbayStartRoute = ApiEbayStartRouteImport.update({
  id: '/api/ebay/start',
  path: '/api/ebay/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectVintedIdRoute = ConnectVintedIdRouteImport.update({
  id: '/connect/vinted/$id',
  path: '/connect/vinted/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVintedConnectSplatRoute = ApiVintedConnectSplatRouteImport.update({
  id: '/api/vinted/connect/$',
  path: '/api/vinted/connect/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sold': typeof AppSoldRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/new': typeof AppNewRoute
  '/sold': typeof AppSoldRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/import': typeof AppImportRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sold': typeof AppSoldRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/channels': typeof AppSettingsChannelsRoute
  '/_app/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/_app/settings/shipping': typeof AppSettingsShippingRoute
  '/_app/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/activity'
    | '/import'
    | '/inbox'
    | '/inventory'
    | '/new'
    | '/settings'
    | '/sold'
    | '/api/worker'
    | '/legal/privacy'
    | '/legal/terms'
    | '/inventory/$id'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/pricing-rules'
    | '/settings/shipping'
    | '/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/inventory/'
    | '/settings/'
    | '/api/vinted/connect/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/activity'
    | '/import'
    | '/inbox'
    | '/new'
    | '/sold'
    | '/api/worker'
    | '/legal/privacy'
    | '/legal/terms'
    | '/inventory/$id'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/pricing-rules'
    | '/settings/shipping'
    | '/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/inventory'
    | '/settings'
    | '/api/vinted/connect/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/download'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/_app/activity'
    | '/_app/import'
    | '/_app/inbox'
    | '/_app/inventory'
    | '/_app/new'
    | '/_app/settings'
    | '/_app/sold'
    | '/api/worker'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_app/inventory/$id'
    | '/_app/settings/billing'
    | '/_app/settings/channels'
    | '/_app/settings/pricing-rules'
    | '/_app/settings/shipping'
    | '/_app/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/_app/inventory/'
    | '/_app/settings/'
    | '/api/vinted/connect/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiWorkerRoute: typeof ApiWorkerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBridgeSplatRoute: typeof ApiBridgeSplatRoute
  ApiEbayCallbackRoute: typeof ApiEbayCallbackRoute
  ApiEbayStartRoute: typeof ApiEbayStartRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ConnectVintedIdRoute: typeof ConnectVintedIdRoute
  ApiVintedConnectSplatRoute: typeof ApiVintedConnectSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sold': {
      id: '/_app/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof AppSoldRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/worker': {
      id: '/api/worker'
      path: '/api/worker'
      fullPath: '/api/worker'
      preLoaderRoute: typeof ApiWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/channels': {
      id: '/_app/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AppSettingsChannelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/pricing-rules': {
      id: '/_app/settings/pricing-rules'
      path: '/pricing-rules'
      fullPath: '/settings/pricing-rules'
      preLoaderRoute: typeof AppSettingsPricingRulesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/shipping': {
      id: '/_app/settings/shipping'
      path: '/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof AppSettingsShippingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/templates': {
      id: '/_app/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AppSettingsTemplatesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/$': {
      id: '/api/bridge/$'
      path: '/api/bridge/$'
      fullPath: '/api/bridge/$'
      preLoaderRoute: typeof ApiBridgeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebay/callback': {
      id: '/api/ebay/callback'
      path: '/api/ebay/callback'
      fullPath: '/api/ebay/callback'
      preLoaderRoute: typeof ApiEbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebay/start': {
      id: '/api/ebay/start'
      path: '/api/ebay/start'
      fullPath: '/api/ebay/start'
      preLoaderRoute: typeof ApiEbayStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/vinted/$id': {
      id: '/connect/vinted/$id'
      path: '/connect/vinted/$id'
      fullPath: '/connect/vinted/$id'
      preLoaderRoute: typeof ConnectVintedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vinted/connect/$': {
      id: '/api/vinted/connect/$'
      path: '/api/vinted/connect/$'
      fullPath: '/api/vinted/connect/$'
      preLoaderRoute: typeof ApiVintedConnectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsChannelsRoute: typeof AppSettingsChannelsRoute
  AppSettingsPricingRulesRoute: typeof AppSettingsPricingRulesRoute
  AppSettingsShippingRoute: typeof AppSettingsShippingRoute
  AppSettingsTemplatesRoute: typeof AppSettingsTemplatesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsChannelsRoute: AppSettingsChannelsRoute,
  AppSettingsPricingRulesRoute: AppSettingsPricingRulesRoute,
  AppSettingsShippingRoute: AppSettingsShippingRoute,
  AppSettingsTemplatesRoute: AppSettingsTemplatesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppImportRoute: typeof AppImportRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSoldRoute: typeof AppSoldRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppImportRoute: AppImportRoute,
  AppInboxRoute: AppInboxRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSoldRoute: AppSoldRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DownloadRoute: DownloadRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiWorkerRoute: ApiWorkerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBridgeSplatRoute: ApiBridgeSplatRoute,
  ApiEbayCallbackRoute: ApiEbayCallbackRoute,
  ApiEbayStartRoute: ApiEbayStartRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ConnectVintedIdRoute: ConnectVintedIdRoute,
  ApiVintedConnectSplatRoute: ApiVintedConnectSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
