/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSoldRouteImport } from './routes/_app.sold'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiMeasurementRouteImport } from './routes/api.measurement'
import { Route as ApiWorkerRouteImport } from './routes/api/worker'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryIdRouteImport } from './routes/_app.inventory.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsChannelsRouteImport } from './routes/_app.settings.channels'
import { Route as AppSettingsPricingRulesRouteImport } from './routes/_app.settings.pricing-rules'
import { Route as AppSettingsShippingRouteImport } from './routes/_app.settings.shipping'
import { Route as AppSettingsTemplatesRouteImport } from './routes/_app.settings.templates'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBridgeSplatRouteImport } from './routes/api/bridge/$'
import { Route as ApiDesktopSplatRouteImport } from './routes/api.desktop.$'
import { Route as ApiEbayCallbackRouteImport } from './routes/api/ebay/callback'
import { Route as ApiEbayStartRouteImport } from './routes/api/ebay/start'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ConnectVintedIdRouteImport } from './routes/connect.vinted.$id'
import { Route as ApiVintedConnectSplatRouteImport } from './routes/api/vinted/connect/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSoldRoute = AppSoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeasurementRoute = ApiMeasurementRouteImport.update({
  id: '/api/measurement',
  path: '/api/measurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerRoute = ApiWorkerRouteImport.update({
  id: '/api/worker',
  path: '/api/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsChannelsRoute = AppSettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPricingRulesRoute = AppSettingsPricingRulesRouteImport.update({
  id: '/pricing-rules',
  path: '/pricing-rules',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShippingRoute = AppSettingsShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTemplatesRoute = AppSettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeSplatRoute = ApiBridgeSplatRouteImport.update({
  id: '/api/bridge/$',
  path: '/api/bridge/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesktopSplatRoute = ApiDesktopSplatRouteImport.update({
  id: '/api/desktop/$',
  path: '/api/desktop/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbayCallbackRoute = ApiEbayCallbackRouteImport.update({
  id: '/api/ebay/callback',
  path: '/api/ebay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbayStartRoute = ApiEbayStartRouteImport.update({
  id: '/api/ebay/start',
  path: '/api/ebay/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectVintedIdRoute = ConnectVintedIdRouteImport.update({
  id: '/connect/vinted/$id',
  path: '/connect/vinted/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVintedConnectSplatRoute = ApiVintedConnectSplatRouteImport.update({
  id: '/api/vinted/connect/$',
  path: '/api/vinted/connect/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/devices': typeof AppDevicesRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sold': typeof AppSoldRoute
  '/api/health': typeof ApiHealthRoute
  '/api/measurement': typeof ApiMeasurementRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/desktop/$': typeof ApiDesktopSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AppAccountRoute
  '/activity': typeof AppActivityRoute
  '/devices': typeof AppDevicesRoute
  '/import': typeof AppImportRoute
  '/inbox': typeof AppInboxRoute
  '/new': typeof AppNewRoute
  '/sold': typeof AppSoldRoute
  '/api/health': typeof ApiHealthRoute
  '/api/measurement': typeof ApiMeasurementRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/desktop/$': typeof ApiDesktopSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/import': typeof AppImportRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sold': typeof AppSoldRoute
  '/api/health': typeof ApiHealthRoute
  '/api/measurement': typeof ApiMeasurementRoute
  '/api/worker': typeof ApiWorkerRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/channels': typeof AppSettingsChannelsRoute
  '/_app/settings/pricing-rules': typeof AppSettingsPricingRulesRoute
  '/_app/settings/shipping': typeof AppSettingsShippingRoute
  '/_app/settings/templates': typeof AppSettingsTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bridge/$': typeof ApiBridgeSplatRoute
  '/api/desktop/$': typeof ApiDesktopSplatRoute
  '/api/ebay/callback': typeof ApiEbayCallbackRoute
  '/api/ebay/start': typeof ApiEbayStartRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/connect/vinted/$id': typeof ConnectVintedIdRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/vinted/connect/$': typeof ApiVintedConnectSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/activity'
    | '/devices'
    | '/import'
    | '/inbox'
    | '/inventory'
    | '/new'
    | '/settings'
    | '/sold'
    | '/api/health'
    | '/api/measurement'
    | '/api/worker'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/inventory/$id'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/pricing-rules'
    | '/settings/shipping'
    | '/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/desktop/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/inventory/'
    | '/settings/'
    | '/api/vinted/connect/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/activity'
    | '/devices'
    | '/import'
    | '/inbox'
    | '/new'
    | '/sold'
    | '/api/health'
    | '/api/measurement'
    | '/api/worker'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/inventory/$id'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/pricing-rules'
    | '/settings/shipping'
    | '/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/desktop/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/inventory'
    | '/settings'
    | '/api/vinted/connect/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/account'
    | '/_app/activity'
    | '/_app/devices'
    | '/_app/import'
    | '/_app/inbox'
    | '/_app/inventory'
    | '/_app/new'
    | '/_app/settings'
    | '/_app/sold'
    | '/api/health'
    | '/api/measurement'
    | '/api/worker'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_app/inventory/$id'
    | '/_app/settings/billing'
    | '/_app/settings/channels'
    | '/_app/settings/pricing-rules'
    | '/_app/settings/shipping'
    | '/_app/settings/templates'
    | '/api/auth/$'
    | '/api/bridge/$'
    | '/api/desktop/$'
    | '/api/ebay/callback'
    | '/api/ebay/start'
    | '/api/stripe/webhook'
    | '/connect/vinted/$id'
    | '/_app/inventory/'
    | '/_app/settings/'
    | '/api/vinted/connect/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeasurementRoute: typeof ApiMeasurementRoute
  ApiWorkerRoute: typeof ApiWorkerRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBridgeSplatRoute: typeof ApiBridgeSplatRoute
  ApiDesktopSplatRoute: typeof ApiDesktopSplatRoute
  ApiEbayCallbackRoute: typeof ApiEbayCallbackRoute
  ApiEbayStartRoute: typeof ApiEbayStartRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ConnectVintedIdRoute: typeof ConnectVintedIdRoute
  ApiVintedConnectSplatRoute: typeof ApiVintedConnectSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sold': {
      id: '/_app/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof AppSoldRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/measurement': {
      id: '/api/measurement'
      path: '/api/measurement'
      fullPath: '/api/measurement'
      preLoaderRoute: typeof ApiMeasurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker': {
      id: '/api/worker'
      path: '/api/worker'
      fullPath: '/api/worker'
      preLoaderRoute: typeof ApiWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/channels': {
      id: '/_app/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AppSettingsChannelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/pricing-rules': {
      id: '/_app/settings/pricing-rules'
      path: '/pricing-rules'
      fullPath: '/settings/pricing-rules'
      preLoaderRoute: typeof AppSettingsPricingRulesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/shipping': {
      id: '/_app/settings/shipping'
      path: '/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof AppSettingsShippingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/templates': {
      id: '/_app/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AppSettingsTemplatesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/$': {
      id: '/api/bridge/$'
      path: '/api/bridge/$'
      fullPath: '/api/bridge/$'
      preLoaderRoute: typeof ApiBridgeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desktop/$': {
      id: '/api/desktop/$'
      path: '/api/desktop/$'
      fullPath: '/api/desktop/$'
      preLoaderRoute: typeof ApiDesktopSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebay/callback': {
      id: '/api/ebay/callback'
      path: '/api/ebay/callback'
      fullPath: '/api/ebay/callback'
      preLoaderRoute: typeof ApiEbayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebay/start': {
      id: '/api/ebay/start'
      path: '/api/ebay/start'
      fullPath: '/api/ebay/start'
      preLoaderRoute: typeof ApiEbayStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/vinted/$id': {
      id: '/connect/vinted/$id'
      path: '/connect/vinted/$id'
      fullPath: '/connect/vinted/$id'
      preLoaderRoute: typeof ConnectVintedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vinted/connect/$': {
      id: '/api/vinted/connect/$'
      path: '/api/vinted/connect/$'
      fullPath: '/api/vinted/connect/$'
      preLoaderRoute: typeof ApiVintedConnectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsChannelsRoute: typeof AppSettingsChannelsRoute
  AppSettingsPricingRulesRoute: typeof AppSettingsPricingRulesRoute
  AppSettingsShippingRoute: typeof AppSettingsShippingRoute
  AppSettingsTemplatesRoute: typeof AppSettingsTemplatesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsChannelsRoute: AppSettingsChannelsRoute,
  AppSettingsPricingRulesRoute: AppSettingsPricingRulesRoute,
  AppSettingsShippingRoute: AppSettingsShippingRoute,
  AppSettingsTemplatesRoute: AppSettingsTemplatesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppActivityRoute: typeof AppActivityRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppImportRoute: typeof AppImportRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSoldRoute: typeof AppSoldRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppActivityRoute: AppActivityRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppImportRoute: AppImportRoute,
  AppInboxRoute: AppInboxRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSoldRoute: AppSoldRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeasurementRoute: ApiMeasurementRoute,
  ApiWorkerRoute: ApiWorkerRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBridgeSplatRoute: ApiBridgeSplatRoute,
  ApiDesktopSplatRoute: ApiDesktopSplatRoute,
  ApiEbayCallbackRoute: ApiEbayCallbackRoute,
  ApiEbayStartRoute: ApiEbayStartRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ConnectVintedIdRoute: ConnectVintedIdRoute,
  ApiVintedConnectSplatRoute: ApiVintedConnectSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
