/** Channel catalogue mirrored from src/lib/lane/channels.ts */
module.exports = {
  vinted_uk: {
    id: "vinted_uk",
    label: "Vinted UK",
    mode: "session",
    origin: "https://www.vinted.co.uk",
    startUrl: "https://www.vinted.co.uk",
    cookieHints: ["refresh_token_web", "access_token_web", "_vinted_fr_session"],
    signedInWhen: (url, names) =>
      names.includes("refresh_token_web") || /\/member\//.test(url) || /wardrobe/.test(url),
  },
  ebay_uk: {
    id: "ebay_uk",
    label: "eBay UK",
    mode: "oauth",
    origin: "https://www.ebay.co.uk",
    startUrl: null,
  },
  depop_uk: {
    id: "depop_uk",
    label: "Depop",
    mode: "session",
    origin: "https://www.depop.com",
    startUrl: "https://www.depop.com/login/",
    cookieHints: ["sessionid", "csrftoken", "depop_session"],
    signedInWhen: (url, names) => names.includes("sessionid") && !/\/login/.test(url),
  },
  facebook_uk: {
    id: "facebook_uk",
    label: "Facebook Marketplace",
    mode: "session",
    origin: "https://www.facebook.com",
    startUrl: "https://www.facebook.com/login",
    cookieHints: ["c_user", "xs", "datr"],
    signedInWhen: (_url, names) => names.includes("c_user") && names.includes("xs"),
  },
  etsy_uk: {
    id: "etsy_uk",
    label: "Etsy UK",
    mode: "oauth",
    origin: "https://www.etsy.com",
    startUrl: null,
  },
  gumtree_uk: {
    id: "gumtree_uk",
    label: "Gumtree",
    mode: "session",
    origin: "https://www.gumtree.com",
    startUrl: "https://www.gumtree.com/login",
    cookieHints: ["GumtreeUser", "session"],
    signedInWhen: (url, names) => names.length > 2 && !/\/login/.test(url),
  },
  shopify: {
    id: "shopify",
    label: "Shopify",
    mode: "oauth",
    origin: "https://admin.shopify.com",
    startUrl: null,
  },
  woocommerce: {
    id: "woocommerce",
    label: "WooCommerce",
    mode: "oauth",
    origin: "https://woocommerce.com",
    startUrl: null,
  },
  grailed: {
    id: "grailed",
    label: "Grailed",
    mode: "session",
    origin: "https://www.grailed.com",
    startUrl: "https://www.grailed.com/login",
    cookieHints: ["_grailed_session"],
    signedInWhen: (url, names) => names.some((n) => /session|auth/i.test(n)) && !/\/login/.test(url),
  },
  whatnot: {
    id: "whatnot",
    label: "Whatnot",
    mode: "oauth",
    origin: "https://www.whatnot.com",
    startUrl: null,
  },
  poshmark: {
    id: "poshmark",
    label: "Poshmark",
    mode: "session",
    origin: "https://poshmark.com",
    startUrl: "https://poshmark.com/login",
    cookieHints: ["_poshmark_session"],
    signedInWhen: (url, names) => names.length > 2 && !/\/login/.test(url),
  },
  mercari: {
    id: "mercari",
    label: "Mercari",
    mode: "session",
    origin: "https://www.mercari.com",
    startUrl: "https://www.mercari.com/login/",
    cookieHints: ["_mercari_session"],
    signedInWhen: (url, names) => names.length > 2 && !/\/login/.test(url),
  },
};
